services:
  SimpleMVC\Service\LoggerService:
    arguments:
      - '%PATH_LOG%'

  SimpleMVC\Core\HTTP\RequestStack: ~

  SimpleMVC\Core\Config: ~

  SimpleMVC\Event\EventDispatcher: ~

  SimpleMVC\Database\Driver\DatabaseInterface: ~
  SimpleMVC\Database\EntityManager: ~
  SimpleMVC\Database\Repository: ~
  SimpleMVC\Database\Migration\Migrator:
    arguments:
      - '@SimpleMVC\Database\Driver\DatabaseInterface'
      - '%PATH_MIGRATIONS%'

  SimpleMVC\Templating\Templating:
    arguments:
      - '%PATH_TEMPLATE%'
      - '%PATH_CACHE%'

  SimpleMVC\Auth\AuthManager:
    arguments:
      - '@SimpleMVC\Database\EntityManager'

  SimpleMVC\Security\PasswordHasher: ~

  # Controllers
  SimpleMVC\Core\HTTP\AbstractController:
    arguments:
        - '@SimpleMVC\Core\HTTP\RequestStack'
        - '@SimpleMVC\Templating\Templating'
        - '@SimpleMVC\Database\Driver\DatabaseInterface'
