services:
  SimpleMVC\Service\LoggerService:
    arguments:
      - '%PATH_LOG%'

  SimpleMVC\Core\HTTP\RequestStack: ~

  SimpleMVC\Core\Config: ~

  SimpleMVC\Core\Container: ~

  SimpleMVC\Event\EventDispatcher: ~

  SimpleMVC\Database\EntityManager:
    arguments:
      - '@SimpleMVC\Database\Driver\DatabaseInterface'

  SimpleMVC\Workflow\WorkflowManager:
    arguments:
      - '@SimpleMVC\Database\EntityManager'

  SimpleMVC\Database\Repository: ~
  SimpleMVC\Database\Migration\Migrator:
    arguments:
      - '@SimpleMVC\Database\Driver\DatabaseInterface'
      - '%PATH_MIGRATIONS%'

  SimpleMVC\Queue\JobRegistry:
    arguments:
      - '@SimpleMVC\Core\Container'

  SimpleMVC\Queue\DatabaseQueueDriver:
    arguments:
      - '@SimpleMVC\Database\Driver\DatabaseInterface'

  SimpleMVC\Templating\Templating:
    arguments:
      - '%PATH_TEMPLATE%'
      - '%PATH_CACHE%'
      - '@SimpleMVC\Core\Container'

  SimpleMVC\Auth\AuthManager:
    arguments:
      - '@SimpleMVC\Database\EntityManager'

  SimpleMVC\Security\PasswordHasher: ~

  SimpleMVC\Debug\DebugToolbar: 
    arguments:
      - '%PATH_VAR%/debug'

  SimpleMVC\Debug\Middleware\DebugToolbarMiddleware:
    arguments:
      - '@SimpleMVC\Debug\DebugToolbar'

  # Controllers
  SimpleMVC\Core\HTTP\AbstractController:
    arguments:
        - '@SimpleMVC\Core\HTTP\RequestStack'
        - '@SimpleMVC\Templating\Templating'
        - '@SimpleMVC\Database\Driver\DatabaseInterface'
  SimpleMVC\Debug\Controller\DebugController:
    arguments:
      - '@SimpleMVC\Core\HTTP\RequestStack'
      - '@SimpleMVC\Templating\Templating'
      - '@SimpleMVC\Database\Driver\DatabaseInterface'
