services:
# Controllers
  App\Controller\HomeController:
    arguments:
      - '@SimpleMVC\Core\HTTP\RequestStack'
      - '@SimpleMVC\Templating\Templating'
      - '@SimpleMVC\Database\Driver\DatabaseInterface'

# Event Listeners
  App\EventListener\LogRequestEventListener:
    arguments:
      - '@SimpleMVC\Service\LoggerService'